### ISSUE TITLE
Lazy person Add-All option?

### ISSUE THREAD

**Issue by Lancaban** [jellyfin/jellyfin-plugin-intros#4]
Lazy person feature request.

I have.... a decent catalog of pre-rolls (just shy of 50). 
after first install, setting up a default rule, clicking each on, then add, then the drop-down, then add etc. got REALLY tedious and tiring.

Would it be possible to create an "add all" button? Or some sort of sensible default for the Base/default rule that included all detected files? 

Again, this is mostly being lazy, but I can imagine someone who has more pre-rolls than me having to sit there and click a few hundred times to get a basic default no frills first run setup. 

It makes a little more sense obviously when you're using the other modes, Tagging, Genres etc. etc. but for the Default it just seems cumbersome.

All that said, LOVE the idea, Love the extra functionality, and I look forward to seeing what comes next :)

**Comment by BrianCArnold** [comment]
That's easily accomplished, I'll try to get it in the next version.

**Comment by Lancaban** [comment]
You are amazing! Thank you :)
