### ISSUE TITLE
Much needed feature requests

### ISSUE THREAD

**Issue by joobert** [jellyfin/jellyfin-plugin-intros#40]
Frankly, pre-rolls are kind of meh at the moment. While the tagging and other features of this plugin are cool, I feel like the development focus is in the wrong place at the moment. 

The fundamentals and overall UX of this plugin are not up to par imho. The implementation is janky (visually), stitched together, and **most importantly _feels_ unnatural.** 

Implementing these overlooked features below would solve SO many issues:
- The ability to hide the playback bar/overlay when an intro starts, is playing, and stay hidden when switching to your content unless the user interacts with it.

- The option to hold off on intro playback until your content has fully loaded and is ready for immediate playback following your intro, creating a seamless gap between the two and mitigating a second round of anticipation after already watching pixels dance around your screen. It goes against human nature to watch an intro followed by "buffering".

In tandem, these features would breathe much needed life back into this plugin and make pre-rolls finally feel cinema in Jellyfin. Hopefully some of you will agree!

**Comment by Beanosss** [comment]
100000% agree. One of the key reasons I moved to Plex.

**Comment by Mihara** [comment]
Thought: Ideally, you would have your prerolls in a format that *no* reasonable client has to transcode, so that they can play while the actual content is gearing up to transcode and conceal this buffering gap.

**Comment by nielsvanvelzen** [comment]
These are feature requests for clients, not this plugin. The plugin just provides intros to the server.
