### ISSUE TITLE
Intros work on movies but not on shows

### ISSUE THREAD

**Issue by vortex91** [jellyfin/jellyfin-plugin-intros#42]
I do not have the check box enabled for movies only. but intros play only for my movies folder.  Am I missing something?

update:  This is due to conflict with a  3rd party plugin.   Can close this ticket.

**Comment by vortex91** [comment]
is playing intros only of first episode of any season normal behavior?  is it possible to h ave it play on all episodes?

**Comment by Obamium69** [comment]
I'm having the same issue

**Comment by LeviSnoot** [comment]
Same issue here. Have tried both having the "Movies Only" checkbox checked and unchecked, behavior is identical in both cases.

Jellyfin Server version: 10.9.8
Local Intros plugin version: 3.0.0.0

**Comment by nielsvanvelzen** [comment]
The plugin just provides intros. It's up to the client to implement playback of them. For example, the Android TV app does not currently play intros for non-movie items.

**Comment by N-Upchurch** [comment]
> I do not have the check box enabled for movies only. but intros play only for my movies folder. Am I missing something?
> 
> update: This is due to conflict with a 3rd party plugin. Can close this ticket.

Which plugin? I am having the same issue on the web client.
