### ISSUE TITLE
Intro only plays for the first episode of a TV Show

### ISSUE THREAD

**Issue by LeviSnoot** [jellyfin/jellyfin-plugin-intros#45]
I'm not sure if this behavior was always present in this plugin, but intros will not play unless you are starting the first item in a TV Show (S01E01, S00E01 etc. depending on which one comes first). I get why you wouldn't want intros for every episode when a user is watching multiple episodes in a row, but it'd be nice if an intro would play every time a "session" starts, regardless of what episode the user decides to play.

**Comment by crobibero** [comment]
The plugin just provides intros. It's up to the client to implement playback of them.

**Comment by Obamium69** [comment]
So none of the clients (I tested Firefox, official Android, Findroid ,Android TV) have implemented the playback of intros before episodes?

**Comment by LeviSnoot** [comment]
> The plugin just provides intros. It's up to the client to implement playback of them.

Understood, so does that mean I should create an issue in the `jellyfin-web` repo or a feature suggestion on Fider?

**Comment by crobibero** [comment]
Sounds like a feature request to me, so https://features.jellyfin.org
